### ISSUE TITLE
Alpine Linux: standard_init_linux.go:207: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by complex64** [goeuro/myke#112]
Myke appears to be incompatible with Alpine Linux!

Any chance this could be a quick fix in cross-compile.sh?

**Dockerfile:**
```dockerfile
FROM alpine:latest
RUN wget -qO /usr/local/bin/myke https://github.com/goeuro/myke/releases/download/v1.0.0/myke_linux_amd64
RUN chmod +x /usr/local/bin/myke
ENTRYPOINT ["/usr/local/bin/myke"]
```
Run returns:
```
standard_init_linux.go:207: exec user process caused "no such file or directory"
```

**Comment by rdsubhas** [comment]
Hi Joe, ooh!! not in the favorite container OS!! :) 

Thanks for reporting, checking it out right away...

**Comment by Sudheerkumar** [comment]
Hi, 
Am getting the same issue. 
Can I please know what is the fix for this ?

am using  
FROM alpine:edge

Is this something related alpine version ?

**Comment by Sudheerkumar** [comment]
Hi,

I am facing the same issue.
am using 
FROM alpine:edge

Is there something related to version of alpine?

**Comment by orhun** [comment]
same here

**Comment by JoseFMP** [comment]
> Quick workaround if you don't mind using the Rust fork, I should really add the polishing and update the README and stuff. But it's stable and has feature parity except for weird _sprig_ stuff.
> 
> ```dockerfile
> FROM alpine:latest
> RUN wget -qO /usr/local/bin/myke https://github.com/fiji-flo/myke/releases/download/0.9.11/myke-0.9.11-x86_64-unknown-linux-musl
> RUN chmod +x /usr/local/bin/myke
> ENTRYPOINT ["/usr/local/bin/myke"]
> ```

For me still failing

**Comment by deepakgd** [comment]
+1
